version: '2'

services:
    php_fpm:
        build:
            context: php_fpm
        container_name: php_fpm
        volumes:
            - ./rc1-linky/:/var/www/html/
        links:
            - mongo

    nginx:
        build:
            context: nginx
        container_name: nginx
        volumes:
            - ./rc1-linky/:/var/www/html/
        links:
            - php_fpm
        ports:
            - 80:80
            - 443:443

    mongo:
        image: mongo
        container_name: mongo
        volumes:
            - ./mongo/data/:/data/db/
            - ./mongo/entrypoint/:/docker-entrypoint-initdb.d
    mysql:
        image: mysql
        container_name: mysql
        restart: always
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: laravel

    api:
        build:
          context: api-docker
        container_name: api
        ports:
          - 1234:80
        volumes:
          - ./api-files/:/var/www/html
